@baseUrl = http://localhost:8080/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVkQXQiOjE3NDAyNTkzMTEsInVzZXJJZCI6IjEifQ.m86q9K_mSJKT_uVbfszxS0PLcCX1j5BsP6hlz51YM3Y

### Register a new user

POST {{baseUrl}}/api/v1/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "test",
    "firstName": "User",
    "lastName": "Test"
}

### Login a user

POST {{baseUrl}}/login
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "test"
}

### Create a new product

POST {{baseUrl}}/products
Content-Type: application/json

{
    "name": "Product 2",
    "description": "Description of product 2",
    "image": "https://via.placeholder.com/150",
    "price": 50,
    "quantity": 10
}

### Get products

GET {{baseUrl}}/products

### Cart checkout

POST {{baseUrl}}/cart/checkout
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "items": [
        {
            "productId": 2,
            "quantity": 2
        }
    ]
}
