services:
  mysql:
    image: mysql:9.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ecom
      MYSQL_USER: ecom
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:
